---
title: "Intro to R_hw3_solutions"
output: html_document
date: "2022-10-07"
---


```{r}
## libraries
library(ggplot2)
library(tidyverse)
library(dplyr)
library(cleaner)
```

### Task 1

```{r}
df2 <- read.csv(url("https://raw.githubusercontent.com/agricolamz/DS_for_DH/master/data/freq_dict_2011.csv"), sep="\t", encoding = "UTF-8")
```

```{r}
letters <- unlist(strsplit(df2$lemma, ""))
letters <- letters[letters != "-"]
letters <- letters[letters != "'"]
```
```{r}
freq.table <- freq(letters)
head(freq.table)
```

```{r}
freq.table <- freq.table[order(freq.table$count,decreasing = TRUE),]
freq.table$item
```

```{r}
# plot
freq.table[c(1:32),] %>%
  ggplot(aes(x=reorder(item, count), y=count))+
  geom_bar(stat="identity")+
  xlab("")+
  ylab("")+
  coord_flip()+
  labs(caption = "дaнные из [Ляшeвcкaя, Шapoв 2011]")+
  theme_bw()
```

### Task 2

```{r}
df <- read.csv(url("https://raw.githubusercontent.com/agricolamz/DS_for_DH/master/data/us_city_average_temperature.csv"))
head(df)
```

```{r}
df <- gather(df, "month", "Temperature", 3:26)
head(df)

df <- df %>%
  separate(month, c("range", "Month"), "_")
df$Month = factor(df$Month, levels = c("january", "february","march" , "april","may", "june", "july", "august", "september","october", "november", "december" ))

head(df)

df$population_2010 <- df$population_2010/1000000
df$Temperature <- (df$Temperature-32)*5/9
head(df)
min(df$Temperature)
```

```{r}
##plot
df %>% 
  ggplot(aes(y=Temperature, x=population_2010, colour=range)) +
  geom_point() +
  ylab("Temperature")+ 
  xlab("Population (mln persons)")+
  facet_wrap(~Month)+
  labs(caption = "data from www.currentresults.com")+
  theme_bw()
```
