### Working with time

[A tutorial](https://cran.r-project.org/web/packages/lubridate/vignettes/lubridate.html)

```{r}
install.packages("tidyverse")
library(tidyverse)

install.packages("lubridate")
library(lubridate)
```

```{r}
today()
now()
```

```{r}
install.packages("nycflights13")
library(nycflights13)
flights
```

#### Creating dates

```{r}
ymd("2022-01-06")
ymd("20-01-21")
ymd("20.01.21")
ymd("20/01/21")
ymd("200121")
mdy("January 21st, 2020")
dmy("21-Jan-2020")
dmy("21 янв 2020", locale = "ru_RU.UTF-8")
dmy("21 янв. 2020", locale = "ru_RU.UTF-8")
dmy("21 ян 2020", locale = "ru_RU.UTF-8")
dmy("21 янва 2020", locale = "ru_RU.UTF-8")
dmy("21 января 2020", locale = "ru_RU.UTF-8")
dmy("21 январь 2020", locale = "ru_RU.UTF-8")
dmy("21 Январь 2020", locale = "ru_RU.UTF-8")
hms("20:01:02")
hm("20.01")
ms("23:59")

flights %>% 
  mutate(departure = make_datetime(year, month, day, hour, minute)) %>% 
  select(departure)
```

#### Extracting parts of the date

```{r}
date_example <- flights$time_hour[1]
date_example

year(date_example)

month(date_example)

month(date_example, label = TRUE)

month(date_example, label = TRUE, abbr = FALSE)

month(date_example, label = TRUE, locale = "ru_RU.UTF-8")

week(date_example)

mday(date_example)

wday(date_example)

wday(date_example, label = TRUE)

wday(date_example, label = TRUE, abbr = FALSE)

wday(date_example, label = TRUE, locale = "ru_RU.UTF-8")

yday(date_example)

hour(date_example)

minute(date_example)

second(date_example)

leap_year(2021)

leap_year(2020)
```

#### Operations with the dates

```{r}
ymd("2020-01-21") - ymd("2020-01-19")

ymd("2020-01-19") - ymd("2020-01-21")

hm("21:00") - hm("18:10")

ymd_hm("2020-01-21, 21:00") - ymd_hm("2020-01-21, 18:10")

ymd_hm("2020-01-21, 21:00") - hm("18:10")

difftime(ymd_hm("2020-01-21, 21:00"), ymd_hm("2020-01-21, 18:10"), units = "mins")

difftime(ymd_hm("2020-01-21, 21:00"), ymd_hm("2020-01-21, 18:10"), units = "hours")

ymd("2019-03-01")+years(1)

ymd("2019-03-01")+dyears(1)

#spring time change
ymd_hms("2020-03-07 13:00:00", tz = "America/New_York") + days(1)
ymd_hms("2020-03-07 13:00:00", tz = "America/New_York") + ddays(1)

#winter time change
ymd_hms("2020-10-31 13:00:00", tz = "America/New_York") + days(1)
ymd_hms("2020-10-31 13:00:00", tz = "America/New_York") + ddays(1)

floor_date(ymd("2020-01-16"), unit = "month")
round_date(ymd("2020-01-16"), unit = "month")
round_date(ymd("2020-01-17"), unit = "month")
ceiling_date(ymd("2020-01-16"), unit = "month")
ceiling_date(ymd("2020-01-16"), unit = "year")
```

#### Depicting time

```{r}
unwelcomed <- read_csv("https://raw.githubusercontent.com/agricolamz/DS_for_DH/master/data/death_of_migrants_and_refugees_from_the_Unwelcomed_project.csv")
unwelcomed %>% 
  mutate(date = dmy(date)) %>% 
  ggplot(aes(date, total_death_missing, color = collapsed_cause))+
  geom_point()+
  scale_y_log10()+
  labs(y = "number of death/missing")

unwelcomed %>% 
  mutate(date = dmy(date)) %>% 
  filter(date < dmy("1-1-2016")) %>% 
  ggplot(aes(date, total_death_missing, color = collapsed_cause))+
  geom_point()+
  scale_y_log10()+
  labs(y = "number of death/missing")

levada <- read_csv("https://raw.githubusercontent.com/agricolamz/DS_for_DH/master/data/2019.01_levada_countries.csv")
levada %>% 
  mutate(date = str_c("1-", date),
         date = dmy(date)) %>% 
  filter(towards == "USA") %>% 
  pivot_longer(names_to = "answer", values_to = "number", good:bad) %>% 
  ggplot(aes(date, number, color = answer))+
  geom_line()+
  labs(x = "", y = "", caption = "данные Левада-центра")+
  scale_y_continuous(limits = c(0, 100))+
  theme(legend.position = c(0.1, 0.9), legend.title = element_blank())
```